name: main-name
on: [push]
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "ths is env=$ENV_1"
        env: 
          ENV_1: hashito
